spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopping?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 689689

  redis:
    host: 127.0.0.1 #192.168.15.129
    port: 6379
    timeout: 180000
  data:
    mongodb:
      host: 127.0.0.1
      database: shoppingdb
      port: 27017
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entity
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
